apiVersion: v1
kind: Secret
metadata:
  name: notification-worker-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  smtp_username: {{ .Values.notificationWorker.secrets.smtpUsername | b64enc | quote }}
  smtp_password: {{ .Values.notificationWorker.secrets.smtpPassword | b64enc | quote }}
  fcm_api_key: {{ .Values.notificationWorker.secrets.fcmApiKey | b64enc | quote }} 