apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.notificationWorker.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.notificationWorker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.notificationWorker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.notificationWorker.name }}
    spec:
      containers:
      - name: {{ .Values.notificationWorker.name }}
        image: {{ .Values.dockerUsername }}/{{ .Values.notificationWorker.image }}:latest
        imagePullPolicy: Always
        env:
        {{- range $key, $value := .Values.notificationWorker.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: notification-worker-secrets
              key: smtp_username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-worker-secrets
              key: smtp_password
        - name: FCM_API_KEY
          valueFrom:
            secretKeyRef:
              name: notification-worker-secrets
              key: fcm_api_key 